# Generated by Django 4.1.1 on 2022-10-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_departure', models.DateTimeField(blank=True)),
                ('dt_arrival', models.DateTimeField(blank=True)),
                ('nm_status', models.CharField(choices=[(0, 'Previsto'), (1, 'Cancelado'), (2, 'Embarcando'), (3, 'Programado'), (4, 'Taxiando Ida'), (5, 'Pronto'), (6, 'Autorizado'), (7, 'Em Voo'), (8, 'Aterrissado'), (9, 'Desembarcando')], default=0, max_length=10)),
                ('dt_creation', models.DateTimeField(auto_now=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('dt_done', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'flight_status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_name', models.CharField(max_length=42)),
                ('nm_role', models.CharField(choices=[(0, 'Piloto'), (1, 'Operador De Voo'), (2, 'Gerente De Operacoes'), (3, 'Controlador De Voo')], max_length=24)),
                ('tx_username', models.CharField(max_length=42)),
                ('tx_hash_key', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_code', models.CharField(max_length=8)),
                ('dt_est_departure', models.DateTimeField()),
                ('dt_est_arrival', models.DateTimeField()),
                ('nm_origin', models.CharField(max_length=3)),
                ('nm_destination', models.CharField(max_length=3)),
                ('fk_flightstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_management.flightstatus')),
            ],
            options={
                'db_table': 'flight',
            },
        ),
    ]
