# Generated by Django 4.1.1 on 2022-11-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fk_flightstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_management.flightstatus'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='nm_destination',
            field=models.CharField(choices=[('BSB', 'Bsb'), ('CGH', 'Cgh'), ('GIG', 'Gig'), ('SSA', 'Ssa'), ('FLN', 'Fln'), ('POA', 'Poa'), ('VCP', 'Vcp'), ('REC', 'Rec'), ('CWB', 'Cwb'), ('BEL', 'Bel'), ('VIX', 'Vix'), ('SDU', 'Sdu'), ('CGB', 'Cgb'), ('CGR', 'Cgr'), ('FOR', 'For'), ('MCP', 'Mcp'), ('MGF', 'Mgf'), ('GYN', 'Gyn'), ('NVT', 'Nvt'), ('MAO', 'Mao'), ('NAT', 'Nat'), ('BPS', 'Bps'), ('MCZ', 'Mcz'), ('PMW', 'Pmw'), ('SLZ', 'Slz'), ('GRU', 'Gru'), ('LDB', 'Ldb'), ('PVH', 'Pvh'), ('RBR', 'Rbr'), ('JOI', 'Joi'), ('UDI', 'Udi'), ('CXJ', 'Cxj'), ('IGU', 'Igu'), ('THE', 'The'), ('AJU', 'Aju'), ('JPA', 'Jpa'), ('PNZ', 'Pnz'), ('CNF', 'Cnf'), ('BVB', 'Bvb'), ('CPV', 'Cpv'), ('STM', 'Stm'), ('IOS', 'Ios'), ('JDO', 'Jdo'), ('IMP', 'Imp'), ('XAP', 'Xap'), ('MAB', 'Mab'), ('CZS', 'Czs'), ('PPB', 'Ppb'), ('CFN', 'Cfb'), ('FEN', 'Fen'), ('JTC', 'Jtc'), ('MOC', 'Moc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='nm_origin',
            field=models.CharField(choices=[('BSB', 'Bsb'), ('CGH', 'Cgh'), ('GIG', 'Gig'), ('SSA', 'Ssa'), ('FLN', 'Fln'), ('POA', 'Poa'), ('VCP', 'Vcp'), ('REC', 'Rec'), ('CWB', 'Cwb'), ('BEL', 'Bel'), ('VIX', 'Vix'), ('SDU', 'Sdu'), ('CGB', 'Cgb'), ('CGR', 'Cgr'), ('FOR', 'For'), ('MCP', 'Mcp'), ('MGF', 'Mgf'), ('GYN', 'Gyn'), ('NVT', 'Nvt'), ('MAO', 'Mao'), ('NAT', 'Nat'), ('BPS', 'Bps'), ('MCZ', 'Mcz'), ('PMW', 'Pmw'), ('SLZ', 'Slz'), ('GRU', 'Gru'), ('LDB', 'Ldb'), ('PVH', 'Pvh'), ('RBR', 'Rbr'), ('JOI', 'Joi'), ('UDI', 'Udi'), ('CXJ', 'Cxj'), ('IGU', 'Igu'), ('THE', 'The'), ('AJU', 'Aju'), ('JPA', 'Jpa'), ('PNZ', 'Pnz'), ('CNF', 'Cnf'), ('BVB', 'Bvb'), ('CPV', 'Cpv'), ('STM', 'Stm'), ('IOS', 'Ios'), ('JDO', 'Jdo'), ('IMP', 'Imp'), ('XAP', 'Xap'), ('MAB', 'Mab'), ('CZS', 'Czs'), ('PPB', 'Ppb'), ('CFN', 'Cfb'), ('FEN', 'Fen'), ('JTC', 'Jtc'), ('MOC', 'Moc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='nm_status',
            field=models.CharField(choices=[('Previsto', 'Previsto'), ('Cancelado', 'Cancelado'), ('Embarcando', 'Embarcando'), ('Programado', 'Programado'), ('Taxiando', 'Taxiando Ida'), ('Pronto', 'Pronto'), ('Autorizado', 'Autorizado'), ('Em Voo', 'Em Voo'), ('Aterrissado', 'Aterrissado'), ('Desembarcando', 'Desembarcando')], default='Previsto', max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='nm_role',
            field=models.CharField(choices=[('Piloto', 'Piloto'), ('Operador de voo', 'Operador De Voo'), ('Gerente de operações', 'Gerente De Operacoes'), ('Controlador de Voo', 'Controlador De Voo')], max_length=24),
        ),
    ]
