# Generated by Django 4.1.1 on 2022-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0002_alter_flight_nm_destination_alter_flight_nm_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
