# Generated by Django 4.1.1 on 2022-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0003_alter_flightstatus_dt_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='dt_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
