# Generated by Django 4.1.1 on 2022-10-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0004_alter_flightstatus_dt_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fk_flightstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_management.flightstatus'),
        ),
    ]
