# Generated by Django 4.1.1 on 2022-11-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0004_alter_user_nm_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nm_role',
            field=models.CharField(choices=[('Piloto', 'Piloto'), ('Operador de voo', 'Operador De Voo'), ('Gerente de operações', 'Gerente De Operacoes'), ('Controlador de Voo', 'Controlador De Voo'), ('Companhia', 'Companhia'), ('Admin', 'Admin')], max_length=24),
        ),
    ]
