# Generated by Django 4.1.1 on 2022-12-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0005_alter_user_nm_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fk_flightstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_management.flightstatus'),
        ),
    ]
