# Generated by Django 4.1.1 on 2022-11-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0005_alter_flight_fk_flightstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightstatus',
            name='nm_status',
            field=models.CharField(choices=[(0, 'Previsto'), (1, 'Cancelado'), (2, 'Embarcando'), (3, 'Programado'), (4, 'Taxiando Ida'), (5, 'Pronto'), (6, 'Autorizado'), (7, 'Em Voo'), (8, 'Aterrissado'), (9, 'Desembarcando')], default='0', max_length=10),
        ),
    ]
