# Generated by Django 4.1.1 on 2022-12-02 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_management', '0006_alter_flight_fk_flightstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fk_flightstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_management.flightstatus'),
        ),
    ]
