from django.db import models

def forDjango(cls):
    cls.do_not_call_in_templates = True
    return cls

class Status(models.TextChoices):
    PREVISTO = "Previsto"
    CANCELADO = "Cancelado"
    EMBARCANDO = "Embarcando"
    PROGRAMADO = "Programado"
    TAXIANDO_IDA = "Taxiando"
    PRONTO = "Pronto"
    AUTORIZADO = "Autorizado"
    EM_VOO = "Em Voo"
    ATERRISSADO = "Aterrissado"
    DESEMBARCANDO = "Desembarcando"

class Role(models.TextChoices):
    PILOTO = "Piloto"
    OPERADOR_DE_VOO = "Operador de voo"
    GERENTE_DE_OPERACOES = "Gerente de operações"
    CONTROLADOR_DE_VOO = "Controlador de Voo"
    COMPANHIA = "Companhia"

class AirportCodes(models.TextChoices):
    BSB = "BSB"
    CGH = "CGH"
    GIG = "GIG"
    SSA = "SSA"
    FLN = "FLN"
    POA = "POA"
    VCP = "VCP"
    REC = "REC"
    CWB = "CWB"
    BEL = "BEL"
    VIX = "VIX"
    SDU = "SDU"
    CGB = "CGB"
    CGR = "CGR"
    FOR = "FOR"
    MCP = "MCP"
    MGF = "MGF"
    GYN = "GYN"
    NVT = "NVT"
    MAO = "MAO"
    NAT = "NAT"
    BPS = "BPS"
    MCZ = "MCZ"
    PMW = "PMW"
    SLZ = "SLZ"
    GRU = "GRU"
    LDB = "LDB"
    PVH = "PVH"
    RBR = "RBR"
    JOI = "JOI"
    UDI = "UDI"
    CXJ = "CXJ"
    IGU = "IGU"
    THE = "THE"
    AJU = "AJU"
    JPA = "JPA"
    PNZ = "PNZ"
    CNF = "CNF"
    BVB = "BVB"
    CPV = "CPV"
    STM = "STM"
    IOS = "IOS"
    JDO = "JDO"
    IMP = "IMP"
    XAP = "XAP"
    MAB = "MAB"
    CZS = "CZS"
    PPB = "PPB"
    CFB = "CFN"
    FEN = "FEN"
    JTC = "JTC"
    MOC = "MOC"